### ISSUE TITLE
Issue in android 6.0

### ISSUE THREAD

**Issue by mehtadakshil** [nicksam112/pokeclone#3]
hi,
i tested the project when launch first time it works fine but when i close app  and open it again i facing error. I am attaching log file .

[Log.txt](https://github.com/nicksam112/pokeclone/files/410814/Log.txt)

**Comment by KayelGee** [comment]
Looks like there is still an issue with the path. Could you try changing the following line in Assets/Models/Tile.cs line 85
`var tilename = Application.persistentDataPath + "/" + realPos.x + "_" + realPos.y;`
to
`var tilename = Path.Combine(Application.persistentDataPath, realPos.x + "_" + realPos.y);`
and report if it fixes the issue?

**Comment by mehtadakshil** [comment]
I Solved it ! I commented following code

if (File.Exists(Application.persistentDataPath + "/" + tilename))
         {
                var r = new StreamReader(tilename, Encoding.Default);
                mapData = new JSONObject(r.ReadToEnd());
            }

**Comment by KayelGee** [comment]
You aren't using the newest version, the lines you posted are already changed in the current version
